public_gsheets_url = "https://docs.google.com/spreadsheets/d/1Cr9CW_l2PmTdpc6hZaqmjgS_hYBblTn3kWBcBIQazDk/edit#gid=0"
public_gsheets_url2 = "https://docs.google.com/spreadsheets/d/1Cr9CW_l2PmTdpc6hZaqmjgS_hYBblTn3kWBcBIQazDk/edit#gid=1274052438"


SHEET_ID = '1Cr9CW_l2PmTdpc6hZaqmjgS_hYBblTn3kWBcBIQazDk'
SHEET_NAME = 'Schedule'